name: audio_recorder_example
version: 1.0.2
description: Demonstrates how to use the audio_recorder plugin.

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.2
  file: ^6.1.2

dev_dependencies:
  audio_recorder:
    path: ../
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true