name: audio_recorder
description: A Flutter plugin to record audio.
version: 1.0.2
homepage: https://github.com/ZaraclaJ/audio_recorder

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  file: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.6
  path_provider: ^2.0.2

flutter:
  plugin:
    platforms:
      android:
        package: com.jordanalcaraz.audiorecorder.audiorecorder
        pluginClass: AudioRecorderPlugin
      ios:
        pluginClass: AudioRecorderPlugin